load("@rules_racket//rules:racket.bzl", "racket_library")

package(default_visibility = ["//visibility:public"])

racket_library(
    name = "proxy_lib",
    srcs = ["proxy_lib.rkt"],
    deps = [
        "//lib:lib",
    ],
)
